import { StyleSheet } from 'react-native';
import { BOTTOM_NAVIGATION_CONTENT_INSET } from '../navigation/navigationLayout';
import { appColors } from '../layout/appColors';

export const calendarStyles = StyleSheet.create({
  screen: { flex: 1 },
  container: {
    flexGrow: 1,
    gap: 14,
    justifyContent: 'flex-start',
    padding: 24,
    paddingBottom: BOTTOM_NAVIGATION_CONTENT_INSET + 34,
    backgroundColor: appColors.background,
  },
  title: { color: appColors.text, fontSize: 24, fontWeight: '700' },
  message: { color: appColors.secondary, fontSize: 15 },
  card: {
    backgroundColor: appColors.surface,
    borderRadius: 20,
    gap: 12,
    padding: 20,
  },
  eventTitle: { color: appColors.text, fontSize: 17, fontWeight: '600' },
  warning: { color: appColors.warning, fontSize: 15 },
  error: { color: appColors.danger, fontSize: 15 },
  calendarMonth: { gap: 12 },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  calendarMonthButton: {
    alignItems: 'center',
    backgroundColor: appColors.primarySoft,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
  },
  calendarMonthButtonText: {
    color: appColors.primaryText,
    fontSize: 24,
    fontWeight: '600',
  },
  calendarMonthTitle: {
    color: appColors.text,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  calendarWeekdayRow: { flexDirection: 'row' },
  calendarWeekday: {
    color: appColors.secondary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    width: '14.2857142857%',
  },
  // Keep weekday labels and date buttons aligned while narrow screens scroll sideways.
  calendarDateGridScroll: { flexGrow: 0, width: '100%' },
  // Seven 44pt day targets stay on one row at the narrowest supported screen width.
  calendarDateGridContent: { gap: 12, minWidth: 308, width: '100%' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', width: '100%' },
  // Content-driven height lets larger accessibility text expand within the ScrollView.
  calendarDay: {
    alignItems: 'center',
    backgroundColor: appColors.surface,
    borderColor: appColors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexShrink: 0,
    gap: 2,
    minHeight: 54,
    minWidth: 44,
    padding: 4,
    width: '14.2857142857%',
  },
  calendarOutsideDay: { opacity: 0.55 },
  calendarSelectedDay: {
    backgroundColor: appColors.primarySoft,
    borderColor: appColors.primary,
    borderWidth: 2,
  },
  calendarDayNumber: { color: appColors.text, fontSize: 15, fontWeight: '600' },
  calendarEventCount: {
    color: appColors.primaryText,
    fontSize: 12,
    fontWeight: '700',
  },
  calendarVisitMarker: {
    color: appColors.warning,
    fontSize: 14,
    fontWeight: '700',
  },
  calendarSelectedDateEvents: { gap: 8 },
  calendarSelectedDate: {
    color: appColors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  calendarEventRow: {
    backgroundColor: appColors.surface,
    borderColor: appColors.border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  calendarNextVisitEvent: {
    backgroundColor: appColors.warningSurface,
    borderLeftColor: appColors.warning,
    borderLeftWidth: 4,
  },
  calendarEventHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  calendarNextVisitBadge: {
    color: appColors.warning,
    fontSize: 13,
    fontWeight: '700',
  },
  calendarSelectEventButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: appColors.primarySoft,
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  calendarSelectEventLabel: {
    color: appColors.primaryText,
    fontSize: 15,
    fontWeight: '600',
  },
  calendarNotice: { color: appColors.warning, fontSize: 14 },
});
