import { StyleSheet } from 'react-native';

export const calendarStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    gap: 14,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#f7f8fa',
  },
  title: { color: '#17212b', fontSize: 24, fontWeight: '700' },
  message: { color: '#45515f', fontSize: 15 },
  card: { backgroundColor: 'white', borderRadius: 10, gap: 8, padding: 14 },
  eventTitle: { color: '#17212b', fontSize: 17, fontWeight: '600' },
  warning: { color: '#8a4b08', fontSize: 15 },
  error: { color: '#a12b25', fontSize: 15 },
  calendarMonth: { gap: 12 },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  calendarMonthButton: {
    alignItems: 'center',
    backgroundColor: '#edf1f5',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
  },
  calendarMonthButtonText: {
    color: '#17212b',
    fontSize: 24,
    fontWeight: '600',
  },
  calendarMonthTitle: {
    color: '#17212b',
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  calendarWeekdayRow: { flexDirection: 'row' },
  calendarWeekday: {
    color: '#687582',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    width: '14.285%',
  },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  // Content-driven height lets larger accessibility text expand within the ScrollView.
  calendarDay: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderColor: '#e0e5ea',
    borderRadius: 8,
    borderWidth: 1,
    flexShrink: 0,
    gap: 2,
    minHeight: 54,
    padding: 4,
    width: '14.285%',
  },
  calendarOutsideDay: { opacity: 0.55 },
  calendarSelectedDay: {
    backgroundColor: '#e7f0ff',
    borderColor: '#3d70b2',
    borderWidth: 2,
  },
  calendarDayNumber: { color: '#17212b', fontSize: 15, fontWeight: '600' },
  calendarEventCount: { color: '#456887', fontSize: 12, fontWeight: '700' },
  calendarVisitMarker: { color: '#87520b', fontSize: 14, fontWeight: '700' },
  calendarSelectedDateEvents: { gap: 8 },
  calendarSelectedDate: {
    color: '#17212b',
    fontSize: 18,
    fontWeight: '700',
  },
  calendarEventRow: {
    backgroundColor: 'white',
    borderColor: '#e0e5ea',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  calendarNextVisitEvent: {
    backgroundColor: '#fff8e8',
    borderLeftColor: '#a56510',
    borderLeftWidth: 4,
  },
  calendarEventHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  calendarNextVisitBadge: {
    color: '#7a4e10',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarSelectEventButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#edf4ff',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  calendarSelectEventLabel: {
    color: '#244f86',
    fontSize: 15,
    fontWeight: '600',
  },
  calendarNotice: { color: '#6b530e', fontSize: 14 },
});
