import { StyleSheet } from 'react-native';

// Shared screen and card styling keeps the review controls visually consistent.
export const visitQuestionReviewStyles = StyleSheet.create({
  container: { gap: 12, padding: 16 },
  title: { color: '#172554', fontSize: 22, fontWeight: '700' },
  appointment: { color: '#334155', fontSize: 15 },
  notice: { color: '#334155', fontSize: 14, lineHeight: 20 },
  error: { color: '#9f1239', fontSize: 14, lineHeight: 20 },
  card: {
    backgroundColor: '#fff',
    borderColor: '#cbd5e1',
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  cardHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  questionNumber: { color: '#172554', fontSize: 17, fontWeight: '700' },
  actions: { flexDirection: 'row', gap: 6 },
  smallButton: {
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  questionInput: {
    borderColor: '#94a3b8',
    borderRadius: 10,
    borderWidth: 1,
    color: '#0f172a',
    fontSize: 16,
    minHeight: 58,
    padding: 10,
    textAlignVertical: 'top',
  },
  rationaleInput: {
    borderColor: '#cbd5e1',
    borderRadius: 10,
    borderWidth: 1,
    color: '#334155',
    fontSize: 14,
    minHeight: 48,
    padding: 10,
    textAlignVertical: 'top',
  },
  priorityButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#eef2ff',
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  buttonText: { color: '#1e3a8a', fontSize: 13, fontWeight: '600' },
  evidenceHeading: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  evidence: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    gap: 4,
    padding: 10,
  },
  evidenceSource: { color: '#475569', fontSize: 12, fontWeight: '600' },
  evidenceContent: { color: '#0f172a', fontSize: 14, lineHeight: 20 },
  footer: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 4,
  },
  secondaryButton: {
    borderColor: '#64748b',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  confirmButton: {
    backgroundColor: '#1d4ed8',
    borderRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  confirmText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  disabledButton: { backgroundColor: '#94a3b8' },
});
