import { StyleSheet } from 'react-native';
import { appColors } from '../layout/appColors';

export const recordingLibraryStyles = StyleSheet.create({
  container: {
    gap: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: appColors.border,
    paddingTop: 12,
  },
  title: { color: appColors.text, fontSize: 18, fontWeight: '700' },
  copy: { color: appColors.secondary, fontSize: 14, lineHeight: 20 },
  list: { gap: 8 },
  item: {
    gap: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: appColors.border,
    borderRadius: 14,
    padding: 12,
    backgroundColor: appColors.surface,
  },
  summaryAction: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 44,
  },
  summaryIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: appColors.primarySoft,
  },
  summaryText: { flex: 1, gap: 2 },
  summaryTitle: { color: appColors.text, fontSize: 16, fontWeight: '700' },
  summaryMetadata: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingLeft: 48,
  },
  reviewBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  reviewNeeds: { backgroundColor: appColors.warningSurface },
  reviewComplete: { backgroundColor: appColors.primarySoft },
  reviewUnavailable: { backgroundColor: appColors.surface },
  reviewNeedsText: {
    color: appColors.warning,
    fontSize: 12,
    fontWeight: '600',
  },
  reviewCompleteText: {
    color: appColors.primaryText,
    fontSize: 12,
    fontWeight: '600',
  },
  reviewUnavailableText: { color: appColors.secondary, fontSize: 12 },
  itemActions: { alignItems: 'flex-end' },
  actions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  detail: {
    gap: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: appColors.border,
    paddingTop: 12,
  },
  detailMetadata: { color: appColors.secondary, fontSize: 14, lineHeight: 20 },
  playbackCard: {
    gap: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: appColors.border,
    borderRadius: 14,
    padding: 12,
    backgroundColor: appColors.surface,
  },
  playbackRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  playbackButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: appColors.primaryAction,
  },
  playbackCopy: {
    flex: 1,
    color: appColors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  playbackTimes: { flexDirection: 'row', justifyContent: 'space-between' },
  deleteProgress: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minHeight: 44,
  },
  error: { color: appColors.danger, fontSize: 14 },
});
